services:
  postgres:
    image: postgres:14.5
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  # server:
  #   image: node:16.14.0-alpine3.14
  #   command:
  #     [
  #       "yarn",
  #       "start"
  #     ]
  #   working_dir: /app
  #   # env_file:
  #   #   - config/docker/env/common.env
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "3000:3000"
  #   restart: unless-stopped

volumes:
  postgres:
